#!/bin/bash
git pull origin master

chmod +x bin/www
npm run build

sudo cp haproxy.cfg /etc/haproxy
sudo systemctl restart haproxy
sudo systemctl status haproxy

sudo systemctl restart mikemaccana.com
sudo systemctl status mikemaccana.com
